/**
 * Environment Variable Injection Script
 * 
 * This script reads .env files and injects environment variables
 * into the HTML file for runtime access.
 * 
 * Usage: node scripts/inject-env.js
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

/**
 * Load environment variables from .env file
 * @param {string} envPath - Path to .env file
 * @returns {Object} Environment variables object
 */
function loadEnvFile(envPath) {
  const env = {};
  
  if (!existsSync(envPath)) {
    console.warn(`Warning: .env file not found at ${envPath}`);
    return env;
  }

  const envContent = readFileSync(envPath, 'utf-8');
  const lines = envContent.split('\n');

  for (const line of lines) {
    // Skip comments and empty lines
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith('#')) {
      continue;
    }

    // Parse KEY=VALUE format
    const equalIndex = trimmedLine.indexOf('=');
    if (equalIndex === -1) {
      continue;
    }

    const key = trimmedLine.substring(0, equalIndex).trim();
    let value = trimmedLine.substring(equalIndex + 1).trim();

    // Remove quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    // Only process VITE_ prefixed variables for Vite projects
    // or REACT_APP_ for React projects
    if (key.startsWith('VITE_') || key.startsWith('REACT_APP_')) {
      env[key] = value;
    }
  }

  return env;
}

/**
 * Write environment variables to an external env.js file
 *
 * D2/C3: replaces the previous inline HTML injection. An inline block with
 * variable content (a) is blocked by the hash-based CSP in royalties.html
 * and (b) dirtied the git tree on every dev start. An external same-origin
 * script is allowed by script-src 'self' and keeps the tree clean.
 *
 * @param {string} outPath - Path to the generated env.js
 * @param {Object} env - Environment variables object
 */
function writeEnvJs(outPath, env) {
  const content = `// AUTO-GENERATED by scripts/inject-env.js — do not edit or commit.
// Source of truth: .env (git-ignored). Loaded before module scripts so
// window.__ENV__ is available to js/utils/config.js at boot.
window.__ENV__ = ${JSON.stringify(env, null, 2)};
`;

  writeFileSync(outPath, content, 'utf-8');
  return true;
}

/**
 * Main function
 */
function main() {
  const envPath = join(rootDir, '.env');
  const envExamplePath = join(rootDir, '.env.example');

  console.log('Generating env.js from environment variables...');

  // Load environment variables
  const env = loadEnvFile(envPath);

  // If .env doesn't exist, check .env.example
  if (Object.keys(env).length === 0 && existsSync(envExamplePath)) {
    console.warn('.env file not found, using .env.example as reference');
    console.warn('Please create a .env file based on .env.example');
  }

  // Always include NODE_ENV
  if (!env.NODE_ENV) {
    env.NODE_ENV = process.env.NODE_ENV || 'development';
  }

  // Write the external env.js (loaded by royalties.html before module scripts)
  if (writeEnvJs(join(rootDir, 'env.js'), env)) {
    console.log('env.js generated successfully');
    console.log(`Loaded ${Object.keys(env).length} environment variables`);
  } else {
    console.error('Failed to generate env.js');
    process.exit(1);
  }
}

// Run if executed directly.
// Note: the previous check (`import.meta.url === \`file://${process.argv[1]}\``)
// never matched on Windows (file:///C:/... vs file://C:\...), so main() never
// ran and env was never injected. pathToFileURL produces the canonical form.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}


